### ISSUE TITLE
Please update file

### ISSUE THREAD

**Issue by Lawrencelotdnd** [A-Series-of-Dice-Based-Events/RiseOfTheRunelords#14]
Someone please remove file book 4/Jorgenfist_Infiltration.pdf, as I have uploaded a newer version.

**Comment by mirkoRainer** [comment]
Sorry this is taking so long. Is the newer version the one with the Secret Tunnel?

**Comment by Lawrencelotdnd** [comment]
Yes that's the newer version, it's being linked to in the readme of book 4

**Comment by mirkoRainer** [comment]
I believe this is resolved.
